# -*- coding: utf-8 -*-
"""Homework6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjpTu10btgA1UYMVfCFaxEySUyiOAhOA

Name: Heather Secrest

Date: 05/12/2026

Course: ST 554 (601)

# **Homework 6**

#**Example Code**
"""

#import some modules needed
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import default_rng
from sklearn import linear_model
rng = default_rng(32)
beta_0 = 7
beta_1 = 1.5
# get three 'values' of x at each integer from 0 to 10.
x = np.array(list(np.linspace(start = 0, stop = 10, num = 11))*3)
n = len(x)
#prepare for the LR fit
reg = linear_model.LinearRegression()
#Create a reg object
#initialize array to save estimates (we don't need beta0 but I'm keeping it!)
beta_array = np.zeros(shape = (5000, 2))
for i in range(5000):
#create the 'responses' modeled from the line plus a random deviation
  y = beta_0 + beta_1*np.array(x) + rng.standard_normal(n)
#find the least squares solutions and store them
  fit = reg.fit(np.array(x).reshape(-1,1), y)
  beta_array[i, :] = [fit.intercept_, fit.coef_[0]]
#visualize the distribution of the slopedata
plt.hist(beta_array[:, 1])
plt.show()
#estimate the probability we are larger than 1.65
bool_prob = beta_array[:, 1] > 1.65
bool_prob.mean()

"""#**Class Code**

Here is my class code.
I started from the beginning and defined all of the things I needed, then did the different methods one by one following the guide in the homework.  

I I decided that sigma was probably the test value used in the last method to find the probability so I used it as that since I couldn't find it in the code above.

I mostly had to edit for syntax errors and I tried to cut down redundant code where I could.
"""

import matplotlib.pyplot as plt
import numpy as np
from numpy.random import default_rng
from sklearn import linear_model

class SLR_slope_simulator:
  #set up my linear model to shortcut as reg

  z=list(np.linspace(start = 0, stop = 10, num = 11))*3
# my __init__ statement. I added initial default variables for
# beat_0, beata_1, and sigma. I did not default the seed because that seems weird
#I also did not default the x so you can input a list of your own x values
#I did however provide an x list from 1-10 following the code above later
#I also decided I needed to set up n and y
#I also added an empty slope list that can be filled later with run_simulations
  def __init__(self, beta_0=7.0, beta_1=1.5, x = list(np.linspace(start = 0, stop = 10, num = 11)*3), sigma=1.65, seed=32):
    self.beta_0 = beta_0
    self.beta_1= beta_1
    self.x = np.array(x)
    self.sigma = sigma
    self.seed = seed
    self.slope = []
    self.rng = default_rng(self.seed)



#I provided an x list from 1-10 following the code above later
#I basically did this according to the above code
  def generate_data(self):
    self.n = len(self.x)
    self.y= self.beta_0 + self.beta_1*self.x + self.rng.standard_normal(self.n)

#For this I just used the reg.fit of x, y to generate my slope of best fit
#I didn't add print functions to either this or the above to avoid cluttering my run_simulations
  def fit_slope(self):
    self.reg = linear_model.LinearRegression()
    self.fit = self.reg.fit(self.x.reshape(-1, 1), self.y)

#I did this basically like the homework said to
#Because the slopes is an empty list,
# I used .append to add to it like my hw 5 code
#I think rounded numbers are prettier in the final view.
  def run_simulations(self, simulations: int):
    self.simulations=simulations
    for i in range(simulations):
      self.generate_data()
      self.fit_slope()
      self.slope.append(self.fit.coef_.round(3))

  #The if else statement controls if this runs or not
  #(aka. it only works if you have already run the above method)
  #I basically just took the plot from the above code
  def plot_sampling_distribution(self):
      if len(self.slope)>0:
        plt.hist(np.array(self.slope))
        plt.show()
      else:
        print('run_simulations must be called first')
#This is the most complicated.
#I wanted two distinct error codes depending on the situation so
# I added nested if else statements.
#The outside one runs a test to see if run_simulation has been done;
#If it hasn't we print run_simulations must be called first.
#My next set does the different test types.
#Above runs if the sided argument is above and does the math.
#Below runs if the sided argument is below and does the math.
#Two-sided is nested again because we do different things if
#the sigma is above or below the median, but again does the math.
#I added an else here to tell the user what arguments were needed
#in case they didn't put in the proper one.
  def find_prob(self, sigma: float, sided: str):
    self.sigma=sigma
    if len(self.slope)>0:
      if sided =='above':
        sum1= len([i for i in self.slope if i > self.sigma])
        prob= sum1/self.simulations
        print(prob)
      elif sided =='below':
        sum1= len([i for i in self.slope if i < self.sigma])
        prob= sum1/self.simulations
        print(prob)
      elif sided == 'two-sided':
        if self.sigma > np.median(np.array(self.slope)):
          sum1= len([i for i in self.slope if i > self.sigma])
          prob= (sum1/self.simulations)*2
          print(prob)
        elif self.sigma < np.median(np.array(self.slope)):
          sum1= len([i for i in self.slope if i < self.sigma])
          prob= sum1/self.simulations
          print(prob)
      else:
        print('Test type argument needed as "above", "below", or "two-sided"')
    else:
        print('run_simulations must be called first')

"""#**Test Code**

This is the code needed to test the class code written above.

I did have an issue with this running differently every time I ran it for a bit, but then realized I forgot to do self.seed in my rng.

This sets up the initial item in the way that the class asks for. It also proves that my error message for `plot_sampling_distribution()` works.
"""

#Creates an instance of the object with beta_0 = 12, beta_1 = 2,
# x = np.array(list(np.linspace(start= 0, stop = 10, num = 11))*3),
# sigma = 1, and seed = 10
SLR1 = SLR_slope_simulator(12,2,x,1,10)
#Call your plot_sampling_distribution() method (this should return the error message)
SLR.plot_sampling_distribution()

"""I ran my simulations with no issue."""

#Runs 10000 simulations
SLR1.run_simulations(10000)

"""This also plotted with little to no issue, although I did have to re-shape the slopes as an array."""

#Plots the sampling distribution
SLR1.plot_sampling_distribution()

"""I also had no issue with this, although I still am not sure what the original sigma was for considering we add one here too?? It also didn't work if I didn't add sigma."""

# Approximates the two-sided probability of being larger than 2.1
SLR1.find_prob(2.1,'two-sided')

"""This also worked perfectly. :)"""

#Prints out the value of the simulated slopes using the attribut
SLR1.slope

"""#**My Additional Tests**

I was having issues with getting the default of my x right, so this was testing that bit of the code. The way I had it originally made it so that x wasn't replaceable I think. This now works. I had to change my self.x = self.x to self.x = x which is just a syntax error.
"""

z= list(np.linspace(start = 0, stop = 12, num = 11))*3
SLR3 = SLR_slope_simulator(12,2,z,1,10)
SLR3.x

"""This was to test the additional error messages I added to find_prob. I needed to make a couple of small changes. I ran it twice (once without running simulations and once with a misspelling of the sides argument)."""

SLR3.find_prob(2.1,'above')